# Generated by Django 5.0.4 on 2024-04-27 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='pno',
            field=models.CharField(max_length=50),
        ),
    ]
